name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Android APK
        uses: GearPlug/cordova-action@v1.1.0
        with:
          command: build android

